version: '3.9'


services:
  ui:
    container_name: ui
    build: 
      context: .
      dockerfile: ./packages/ui/Dockerfile
    ports:
      - 3000:3000
  graphql:
    container_name: graphql
    build: 
      context: .
      dockerfile: ./packages/graphql/Dockerfile
    ports:
      - 3001:3001
  mongo:
    container_name: db
    image: mongo
    ports:
      - 27018:27017